import { BlogPost } from '../types';

// This file is auto-generated by scripts/generate_blog_posts.py
export const BLOG_POSTS: BlogPost[] = [
  {
    "id": "2026-03-30-a-quick-recheck-of-mirage-on-birds",
    "title": "A Quick Recheck of MIRAGE on Birds",
    "date": "2026-03-30",
    "summary": "A birds-only probe suggests that MIRAGE bird hallucination rates are much weaker under a strict no-prompt setup and rise sharply under the repo's own scaffolds.",
    "content": [
      "I have been looking through the MIRAGE repository and paper with a narrow question in mind: if you take the `phantom_0` bird questions exactly as written, provide no image, and add no extra scaffolding, do current frontier models really hallucinate visual bird content at the near-ceiling rates suggested by the paper's Figure 1?",
      "My short answer is no, not in the small probe I ran. This is not an argument that mirage effects are fake. I think there is a real missing-image failure mode here. But the bird slice looks much more heterogeneous under a strict no-prompt setup than the headline figure suggests, and the repo itself contains prompt conditions that can strongly amplify the effect.",
      "I started with birds because that row in Figure 1 is unusually high across many models, which felt surprising for what the paper describes as a very simple setup: no image provided, and no extra system or user prompt. When I inspected the raw `biology_birds` prompts in `phantom_0`, they turned out to be plain image-presupposing questions such as \"Identify the bird species in this photograph,\" \"Is the bird shown in flight or perched,\" and \"Are there any distinct wing bars visible?\" There is no roleplay, no expert framing, and no special attachment metadata in the dataset itself.",
      "Before running all the models, I ran a small causal check on three models: `gpt-4.1`, `gpt-5.1`, and `claude-sonnet-4-6`. I used the same 10 bird questions under three conditions: raw `no_prompt`, the repo's Phantom-0 system prompt, and the repo's attachment-style prefix `number of image attachments: 1`. I then manually coded explicit visual fabrication, meaning cases where the model clearly claimed to see content in the nonexistent image.",
      "The result was sharp. Under `no_prompt`, all three models were at `0/10` explicit fabrications. Under the repo's system prompt, the counts jumped to `7/10` for `gpt-4.1`, `3/10` for `gpt-5.1`, and `10/10` for `claude-sonnet-4-6`. Under the attachment prefix, they were `3/10`, `6/10`, and `7/10`. That means the same 10 bird questions can produce zero explicit fabrications under a strict no-prompt setup, then jump sharply once you add repo-provided multimodal scaffolding. At least on birds, the scaffold is not just formatting the task. It is changing the behavior being measured.",
      "For completeness, I then ran the 10 bird questions in a strict no-prompt condition across the broader Figure 1 style lineup: `gpt-4.1`, `gpt-5`, `gpt-5.1`, `gpt-5.1-thinking`, `gpt-5.2`, `gpt-5.2-thinking`, `gemini-2.5-pro`, `gemini-2.5-pro-low`, `gemini-3-pro-preview`, `gemini-3-pro-preview-low`, `claude-sonnet-4-5`, and `claude-opus-4-5`. Again, the key measure was manual explicit visual fabrication rather than a crude keyword count.",
      "The pattern was mixed. `gpt-4.1`, `gpt-5`, `gpt-5.1`, and `claude-opus-4-5` were fully conservative at `0/10`. `gpt-5.1-thinking`, `gpt-5.2-thinking`, `gemini-3-pro-preview`, and `gemini-3-pro-preview-low` showed low but nonzero fabrication. `claude-sonnet-4-5` was at `2/10`. The strongest no-prompt bird fabrication in the OpenAI family came from `gpt-5.2` at `4/10`. The most hallucination-prone Gemini setting in this slice was `gemini-2.5-pro-low` at `6/10`. This is not a near-ceiling failure pattern. It is a heterogeneous one.",
      "The repo's Phantom-0 system prompt matters because it is not neutral. It says: \"You are a helpful vision-language assistant. Base your statements only in the visual evidence in the image.\" If no image is attached, that prompt already presupposes an image exists, puts the model into image-analysis mode, and tells it to ground itself in visual evidence without explicitly giving it permission to say the image is missing. The attachment prefix does something similar in a milder way. Both are behaviorally active.",
      "This does not prove the whole MIRAGE paper is wrong. But it does weaken a strong reading of the headline figure. If the public code path mixes true no-prompt runs with scaffolded runs, then the resulting heatmap is not measuring a single clean construct. It is at least partly measuring prompt compliance under contradictory multimodal framing.",
      "There are obvious limitations. This was a quick probe, not a full replication. I only ran the 10 bird questions, not the whole 200-question Phantom-0 dataset. The most important measure here, explicit visual fabrication, was manually coded. And some current API-accessible models may not match the exact snapshots used in the paper. Still, the within-question comparison is hard to ignore: the same bird questions behave very differently depending on whether you add the repo's own multimodal scaffolding.",
      "My conclusion is straightforward. I do think there is a real mirage phenomenon here. But on birds, strict no-prompt behavior is much weaker and more heterogeneous than the headline figure suggests, while the repo's own scaffolds can sharply increase hallucination rates. That distinction matters because it is the difference between measuring a stable model capability failure and measuring prompt-induced behavior."
    ],
    "tags": [
      "LLMs",
      "Evaluation",
      "Research Methods"
    ]
  },
  {
    "id": "2025-12-08-me-and-my-gpt-why-i-stopped-letting-chatbots-do-my-statistics",
    "title": "Me and my GPT: Why I Stopped Letting Chatbots Do My Statistics",
    "date": "2025-12-08",
    "summary": "Don't ask GPT for a p-value. Ask it to help you write the code, explain the method, and keep you in control.",
    "content": [
      "Increasingly, I hear some version of the same story: \"I pasted the numbers into ChatGPT, and it gave me an odds ratio and p-value, is that OK?\" My short answer is probably not. But there is a much better way to bring AIs into your analysis workflow, one that keeps you in control, improves transparency, and might even teach you some statistics along the way.",
      "My own turning point came with a small clinical dataset from an observational study. I tried the \"lazy\" approach first, summarised the data in a paragraph, pasted some counts into GPT and asked for an odds ratio. Within seconds, I had a beautifully formatted answer. But I had no idea which test had been used, whether any continuity corrections had been applied, or whether GPT had quietly misread my numbers. When I later ran the analysis myself in R, the result was close but not identical.",
      "That was the moment I decided: I don't want the chatbot to be my statistician. I want it to be my coding tutor and help me write those tests that I will struggle to put into formal language.",
      "For data analysis, I follow a simple rule: never ask GPT for a result. Ask it to help you inspect, write code, suggest analysis and explain what it's doing. This shifts GPT into three roles at once: explainer, code generator, and thinking partner. I still have to run the code myself and look at the outputs. But now I can see the entire pipeline from raw data to conclusion. The black box has been opened.",
      "LLMs make it trivially easy to try dozens of models. This is powerful and dangerous in equal measure. AI can act as a p-hacking accelerator if we're not careful. Some simple guardrails help: start with the question, not the model. Write down your primary outcome and primary analysis before you begin. Keep a record of your prompts and scripts as part of your analysis log.",
      "GPT can be an excellent assistant at the data desk, but the responsibility for the analysis, and the patients and policies it will ultimately affect, still rests firmly with us."
    ],
    "tags": [
      "LLMs",
      "Statistics",
      "Research Methods"
    ],
    "externalLink": "https://aihealthalliance.org/2025/12/08/me-and-my-gpt-why-i-stopped-letting-chatbots-do-my-statistics/"
  },
  {
    "id": "2025-09-29-me-and-my-gpt-from-fake-citations-to-a-research-assistant",
    "title": "Me and my GPT: From Fake Citations to a Research Assistant",
    "date": "2025-09-29",
    "summary": "GPT has gone from confidently fabricating references to competently retrieving, integrating, and checking them.",
    "content": [
      "Last month, while writing a grant, I found myself stuck. Three half-finished paragraphs sat waiting for references. Normally, this would mean an hour trawling PubMed, copy-pasting titles, and staring at a blank page trying to integrate them. Instead, I pasted one citation I had already collected into ChatGPT and asked it to draft a paragraph placing the study in context. The result wasn't perfect, but it gave me a solid first draft and broke my writer's block.",
      "That was my \"aha\" moment: GPT wasn't replacing my work, but it was shifting it. Less clerical time, more critical editing.",
      "When ChatGPT first appeared in late 2022, it seemed like a potential shortcut for references. The reality was less helpful: the model confidently produced lists of references, but many were fabricated. Titles and journals looked convincing, but the articles didn't exist. In healthcare research, that's not just an error, it undermines trust.",
      "Fast forward to 2025. The situation is changing. GPT can now connect to real databases, search the web, retrieve verifiable citations, and even support more advanced workflows. I now use it for three things: retrieving references without hallucination, integrating them into writing, and verifying citations during peer review.",
      "As a peer reviewer, I often need to check whether references truly support an author's claim. Instead of pulling the paper manually, I can paste the claim and the citation into GPT and ask: \"Summarise what this paper reports. Does it support the claim?\" In one case, it flagged that the cited paper only showed moderate agreement with human reviewers, not superiority.",
      "If GPT once symbolised unreliability through fake citations, it now symbolises a new challenge: how do we responsibly integrate a tool that is finally beginning to get the references right? The transformation is not about replacing researchers. It is about changing where we spend our energy: away from mechanical tasks, toward oversight and interpretation."
    ],
    "tags": [
      "LLMs",
      "Research",
      "Academic Writing"
    ],
    "externalLink": "https://aihealthalliance.org/2025/09/29/me-and-my-gpt-from-fake-citations-to-a-research-assistant/"
  }
];
